// Catálogo único de códigos de erro (Anexo C)
export const CODIGOS_ERRO = {
  IDENTIFICADOR_INVALIDO: { status: 400, mensagem: 'Identificador inválido' },
  PARAMETRO_INVALIDO: { status: 400, mensagem: 'Parâmetro inválido' },
  NAO_AUTENTICADO: { status: 401, mensagem: 'Requisição não autenticada' },
  CREDENCIAIS_INVALIDAS: { status: 401, mensagem: 'E-mail ou senha inválidos' },
  PRODUTO_NAO_ENCONTRADO: { status: 404, mensagem: 'Produto não encontrado' },
  CATEGORIA_NAO_ENCONTRADA: { status: 404, mensagem: 'Categoria não encontrada' },
  UNIDADE_NAO_ENCONTRADA: { status: 404, mensagem: 'Unidade de medida não encontrada' },
  EMAIL_JA_CADASTRADO: { status: 409, mensagem: 'E-mail já cadastrado' },
  SKU_DUPLICADO: { status: 409, mensagem: 'Já existe um produto com este SKU' },
  EAN13_DUPLICADO: { status: 409, mensagem: 'Já existe um produto com este código EAN-13' },
  NOME_DUPLICADO_NA_CATEGORIA: { status: 409, mensagem: 'Já existe um produto com este nome nesta categoria' },
  SKU_IMUTAVEL: { status: 409, mensagem: 'O SKU não pode ser alterado após o cadastro' },
  PRODUTO_COM_HISTORICO: { status: 409, mensagem: 'Produto possui histórico de preço e não pode ser excluído' },
  EXCLUSAO_NAO_PERMITIDA: { status: 409, mensagem: 'Exclusão física desabilitada. Utilize a inativação do produto' },
  CATEGORIA_COM_PRODUTO_ATIVO: { status: 409, mensagem: 'Categoria possui produtos ativos vinculados' },
  NOME_CATEGORIA_DUPLICADO: { status: 409, mensagem: 'Já existe uma categoria com este nome' },
  SIGLA_UNIDADE_DUPLICADA: { status: 409, mensagem: 'Já existe uma unidade de medida com esta sigla' },
  PRODUTO_JA_ATIVO: { status: 409, mensagem: 'O produto já está ativo' },
  PRODUTO_JA_INATIVO: { status: 409, mensagem: 'O produto já está inativo' },
  VALIDACAO: { status: 422, mensagem: 'Dados inválidos' },
  ERRO_INTERNO: { status: 500, mensagem: 'Erro interno do servidor' },
};
